steps:
  # build the docker image
  #   - name: 'gcr.io/cloud-builders/docker'
  #     args: ['build', '-t', 'gcr.io/${PROJECT_ID}/cicd:${SHORT_SHA}', '.']
  #     # tag docker image with commit sha
  #     id: 'docker build'
  # run the spectacles incremental sql tests
  - name: 'gcr.io/cloud-builders/docker'
    env:
    - '_HEAD_BRANCH=$_HEAD_BRANCH'
    - '_BASE_BRANCH=$_BASE_BRANCH'
    - 'PROJECT_ID=$PROJECT_ID'
    entrypoint: 'bash'
    args:
      - -c
      - |
          docker run -e _HEAD_BRANCH=${_HEAD_BRANCH} -e _BASE_BRANCH=${_BASE_BRANCH} -e SPECTACLES_ID=$$SPECTACLES_ID -e SPECTACLES_SECRET=$$SPECTACLES_SECRET us-west1-docker.pkg.dev/${PROJECT_ID}/spectacles-test/spectacles-sql-validator:v1
    id: 'test-sql'
    secretEnv: ['SPECTACLES_ID', 'SPECTACLES_SECRET']
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/spectacles_id/versions/1
    env: 'SPECTACLES_ID'
  - versionName: projects/${PROJECT_ID}/secrets/spectacles_secret/versions/1
    env: 'SPECTACLES_SECRET'
