steps:
  - name: >-
      us-west1-docker.pkg.dev/${PROJECT_ID}/spectacles-test/spectacles-sql-validator:v1
    env:
      - _HEAD_BRANCH=$_HEAD_BRANCH
      - _BASE_BRANCH=$_BASE_BRANCH
      - PROJECT_ID=$PROJECT_ID
    id: test-sql
    secretEnv:
      - SPECTACLES_ID
      - SPECTACLES_SECRET
availableSecrets:
  secretManager:
    - versionName: 'projects/${PROJECT_ID}/secrets/spectacles_id/versions/1'
      env: SPECTACLES_ID
    - versionName: 'projects/${PROJECT_ID}/secrets/spectacles_secret/versions/1'
      env: SPECTACLES_SECRET
